networks:
  internal-network:
    driver: bridge
    internal: true
  internet:
    driver: bridge
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - pgdata:${POSTGRES_PGDATA}
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    image: "backend"
    ports:
      - "4000:3000"
    depends_on:
      - postgres
    links:
      - postgres
    env_file:
      - ./backend/.env
  frontend:
    depends_on:
      - backend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    image: "frontend"
    ports:
      - '8081:80'

volumes:
  pgdata: